{% set version = "1.37.0" %}
{% set name = "SpikeInSubset" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: acfc16b524f4a8862281006722f3f32a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-affy >=1.76.0,<1.77.0'
    - 'bioconductor-biobase >=2.58.0,<2.59.0'
    - r-base
  run:
    - 'bioconductor-affy >=1.76.0,<1.77.0'
    - 'bioconductor-biobase >=2.58.0,<2.59.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: LGPL
  summary: 'Part of Affymetrix''s Spike-In Experiment Data'
  description: 'Includes probe-level and expression data for the HGU133 and HGU95 spike-in experiments'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

