{% set version = "20180710" %}

package:
  name: rascaf
  version: {{ version }}

build:
  # scaffold.hpp:722:32: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
  skip: True  # [osx]
  number: 8
  run_exports:
    - {{ pin_subpackage(name|lower) }}

source:
  url: https://github.com/mourisl/Rascaf/archive/690f618e59b1f555fafa406ad1b6b95c1b0423b4.tar.gz
  md5: 7478d8db1e4f5618ee9ab0dfae23815f
  patches:
    - 0001-Unvendor-samtools.patch

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - samtools 0.1.19.*
    - zlib
  run:
    - zlib

test:
  commands:
    - rascaf 2>&1 | grep usage > /dev/null
    - rascaf-join 2>&1 | grep usage > /dev/null

about:
  home: https://github.com/mourisl/Rascaf/commits/master
  summary: Scaffolding with RNA-seq read alignment
  license: GPL2
