{% set version = "0.43.0" %}
{% set name = "yeastExpData" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 83706c49ab5d73657adb5927b2514eed
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: Biobase, GO.db, RBGL, org.Sc.sgd.db
requirements:
  host:
    - 'bioconductor-graph >=1.76.0,<1.77.0'
    - r-base
  run:
    - 'bioconductor-graph >=1.76.0,<1.77.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL
  summary: 'Yeast Experimental Data'
  description: 'A collection of different sets of experimental data from yeast.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  parent_recipe:
    name: bioconductor-yeastexpdata
    path: recipes/bioconductor-yeastexpdata
    version: 0.26.0

