{% set version = "1.3.0" %}
{% set name = "scanMiRData" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a43695113a97f647b5d126ed6a25e916
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, BiocStyle
requirements:
  host:
    - 'bioconductor-scanmir >=1.4.0,<1.5.0'
    - r-base
  run:
    - 'bioconductor-scanmir >=1.4.0,<1.5.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-3
  summary: 'miRNA Affinity models for the scanMiR package'
  description: 'This package contains companion data to the scanMiR package. It contains `KdModel` (miRNA 12-mer binding affinity models) collections corresponding to all human, mouse and rat mirbase miRNAs. See the scanMiR package for details.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

