{% set name = "portcullis" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/maplesond/portcullis/archive/{{ version }}.tar.gz
  sha256: 7848167529cb1775382ebc759d08880e99e1691ede0a8c6e474cbb9109603426

build:
  number: 3
  skip: True # [osx or py27]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake >=1.15.1
    - libtool
    - perl
  host:
    - zlib
    - pandas
    - python
    - samtools >=1.9
    - boost-cpp
  run:
    - python
    - boost-cpp
    - tabulate
    - numpy
    - pandas
    - samtools >=1.9

test:
  commands:
    - portcullis --version
    - junctools --help  

about:
  home: https://github.com/maplesond/portcullis
  license: GPL3
  license_file: COPYING
  summary: 'Splice junction analysis and filtering from BAM files'
