{% set name = "portcullis" %}
{% set version = "1.2.2" %}
{% set sha256 = "8e7f187feaf49aa393e8603817454d440d0fe2700250bfb2c9cd4524f3fcab32" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/maplesond/portcullis/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: True # [osx or py27]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake >=1.15.1
    - libtool
    - perl
  host:
    - zlib
    - pandas
    - python
    - samtools >=1.9
    - boost-cpp
  run:
    - python
    - boost-cpp
    - tabulate
    - numpy
    - pandas
    - samtools >=1.9

test:
  commands:
    - portcullis --version
    - junctools --help  

about:
  home: https://github.com/maplesond/portcullis
  license: GPL3
  license_file: COPYING
  summary: 'Splice junction analysis and filtering from BAM files'
