{% set version = "0.35.0" %}
{% set name = "lungExpression" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 49cd2379de1eaa83e01fd979be94ee79
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-biobase >=2.58.0,<2.59.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.58.0,<2.59.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'ExpressionSets for Parmigiani et al., 2004 Clinical Cancer Research paper'
  description: 'Data from three large lung cancer studies provided as ExpressionSets'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

