{% set version = "1.5.0" %}
{% set name = "TENxVisiumData" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 9fe57094f0c7e344a01a80277736c84b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, rmarkdown
requirements:
  host:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - 'bioconductor-spatialexperiment >=1.8.0,<1.9.0'
    - r-base
  run:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - 'bioconductor-spatialexperiment >=1.8.0,<1.9.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Visium spatial gene expression data by 10X Genomics'
  description: 'Collection of Visium spatial gene expression datasets by 10X Genomics, formatted into objects of class SpatialExperiment. Data cover various organisms and tissues, and include: single- and multi-section experiments, as well as single sections subjected to both whole transcriptome and targeted panel analysis. Datasets may be used for testing of and as examples in packages, for tutorials and workflow demonstrations, or similar purposes.'
  license_file: LICENSE

