{% set version = "0.6.0" %}
{% set github = "https://github.com/acidgenomics/r-goalie" %}

package:
  name: r-goalie
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 34b78bd1877b855dd3510cf8591924b25c6569b51c73af10cc8ce24e6d065d5b
  
build:
  number: 1
  noarch: generic

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('goalie')"

about:
  home: https://r.acidgenomics.com/packages/goalie/
  dev_url: "{{ github }}"
  license: AGPL-3
  license_file: LICENSE
  license_family: GPL
  summary: Assertive check functions for defensive R programming.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
