{% set version = "1.13.0" %}
{% set name = "adductData" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: f7bdef108829e66360d9980a094c076c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr (>= 1.15.1), rmarkdown (>= 1.5)
requirements:
  host:
    - 'bioconductor-annotationhub >=3.6.0,<3.7.0'
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - r-base
  run:
    - 'bioconductor-annotationhub >=3.6.0,<3.7.0'
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Data from untargeted MS of modifications to Cys34 of serum albumin'
  description: 'mzXML files from Grigoryan et al 2016 (Anal Chem).'

