{% set version = "1.27.0" %}
{% set name = "QDNAseq.hg19" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 518d77883a6b46e2f874be69d84d4f68
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-qdnaseq >=1.34.0,<1.35.0'
    - r-base
  run:
    - 'bioconductor-qdnaseq >=1.34.0,<1.35.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL
  summary: 'QDNAseq bin annotation for hg19'
  description: 'This package provides QDNAseq bin annotations for the human genome build hg19.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

