{% set version = "1.35.0" %}
{% set name = "MAQCsubsetILM" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 41a6ad9c3dfb6007756cc5a52077e226
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-biobase >=2.58.0,<2.59.0'
    - 'bioconductor-lumi >=2.50.0,<2.51.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.58.0,<2.59.0'
    - 'bioconductor-lumi >=2.50.0,<2.51.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'MAQC data subset for the Illumina platform'
  description: 'MAQC data subset for the Illumina platform'

