{% set version = "1.33.0" %}
{% set name = "SomaticCancerAlterations" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 1974e96d47df6f7fde09f8e0eb069ac5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat, ggbio, ggplot2, knitr
requirements:
  host:
    - 'bioconductor-genomicranges >=1.50.0,<1.51.0'
    - 'bioconductor-iranges >=2.32.0,<2.33.0'
    - 'bioconductor-s4vectors >=0.36.0,<0.37.0'
    - r-base
  run:
    - 'bioconductor-genomicranges >=1.50.0,<1.51.0'
    - 'bioconductor-iranges >=2.32.0,<2.33.0'
    - 'bioconductor-s4vectors >=0.36.0,<0.37.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-3
  summary: 'Somatic Cancer Alterations'
  description: 'Collection of somatic cancer alteration datasets'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

