{% set version = "1.37.0" %}
{% set name = "dyebiasexamples" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: 9875c284f5e3b185f712ffac9b5f885d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: dyebias, convert, Biobase
requirements:
  host:
    - 'bioconductor-geoquery >=2.66.0,<2.67.0'
    - 'bioconductor-marray >=1.76.0,<1.77.0'
    - r-base
  run:
    - 'bioconductor-geoquery >=2.66.0,<2.67.0'
    - 'bioconductor-marray >=1.76.0,<1.77.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-3
  summary: 'Example data for the dyebias package, which implements the GASSCO method.'
  description: 'Data for the dyebias package, consisting of 4 self-self hybrizations of self-spotted yeast slides, as well as data from Array Express accession E-MTAB-32'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

