{% set version = "2.32" %}
{% set sha256 = "58b90e8908e686d03a161590c1dd870e8a1b005715ca8e6d5080a32459e1e9f8" %}

package:
  name: perl-termreadkey
  version: '{{ version }}'

source:
  url: https://cpan.metacpan.org/authors/id/J/JS/JSTOWE/TermReadKey-2.32.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 1
  run_exports:
    - {{ pin_subpackage('perl-termreadkey', max_pin='x.x') }}

requirements:
  build:
    - perl-threaded
    - gcc

  run:
    - perl-threaded
    - libgcc

test:
  # Perl 'use' tests
  imports:
    - Term::ReadKey

about:
  home: http://metacpan.org/pod/TermReadKey
  license: perl_5
  summary: 'A perl module for simple terminal control'
