{% set version = "1.17.0" %}
{% set name = "ChIC.data" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: bb4837e672e71ea19f267efb7c73e628
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-genomeintervals >=1.54.0,<1.55.0'
    - r-base
    - 'r-caret >=6.0-78'
    - r-randomforest
  run:
    - 'bioconductor-genomeintervals >=1.54.0,<1.55.0'
    - r-base
    - 'r-caret >=6.0-78'
    - r-randomforest
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: 'ChIC package data'
  description: 'This package contains annotation and metagene profile data for the ChIC package.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

