{% set version = "2.15.0" %}
{% set name = "DMRcatedata" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 33cd820499c1fb6488cdef2b2ef7e95a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr
requirements:
  host:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - 'bioconductor-genomicfeatures >=1.50.0,<1.51.0'
    - 'bioconductor-gviz >=1.42.0,<1.43.0'
    - 'bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19 >=0.6.0,<0.7.0'
    - 'bioconductor-illuminahumanmethylationepicanno.ilm10b4.hg19 >=0.6.0,<0.7.0'
    - 'bioconductor-rtracklayer >=1.58.0,<1.59.0'
    - r-base
    - r-plyr
    - r-readxl
  run:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - 'bioconductor-genomicfeatures >=1.50.0,<1.51.0'
    - 'bioconductor-gviz >=1.42.0,<1.43.0'
    - 'bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19 >=0.6.0,<0.7.0'
    - 'bioconductor-illuminahumanmethylationepicanno.ilm10b4.hg19 >=0.6.0,<0.7.0'
    - 'bioconductor-rtracklayer >=1.58.0,<1.59.0'
    - r-base
    - r-plyr
    - r-readxl
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-3
  summary: 'Data Package for DMRcate'
  description: 'This package contains 9 data objects supporting functionality and examples of the Bioconductor package DMRcate.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  parent_recipe:
    name: bioconductor-dmrcatedata
    path: recipes/bioconductor-dmrcatedata
    version: 1.16.0

