{% set version = "1.47.0" %}
{% set name = "ArrayExpressHTS" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a737adbd619efab5b847cae073a55848
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# SystemRequirements: GNU make
requirements:
  host:
    - 'bioconductor-biobase >=2.58.0,<2.59.0'
    - 'bioconductor-biocgenerics >=0.44.0,<0.45.0'
    - 'bioconductor-biomart >=2.54.0,<2.55.0'
    - 'bioconductor-biostrings >=2.66.0,<2.67.0'
    - 'bioconductor-edger >=3.40.0,<3.41.0'
    - 'bioconductor-genomicranges >=1.50.0,<1.51.0'
    - 'bioconductor-iranges >=2.32.0,<2.33.0'
    - 'bioconductor-rhtslib >=2.0.0,<2.1.0'
    - 'bioconductor-rsamtools >=2.14.0,<2.15.0'
    - 'bioconductor-shortread >=1.56.0,<1.57.0'
    - r-base
    - r-bitops
    - r-hmisc
    - r-r2html
    - r-rcolorbrewer
    - r-rjava
    - r-sampling
    - r-sendmailr
    - r-snow
    - r-svmisc
    - r-xml
    - libblas
    - liblapack
  run:
    - 'bioconductor-biobase >=2.58.0,<2.59.0'
    - 'bioconductor-biocgenerics >=0.44.0,<0.45.0'
    - 'bioconductor-biomart >=2.54.0,<2.55.0'
    - 'bioconductor-biostrings >=2.66.0,<2.67.0'
    - 'bioconductor-edger >=3.40.0,<3.41.0'
    - 'bioconductor-genomicranges >=1.50.0,<1.51.0'
    - 'bioconductor-iranges >=2.32.0,<2.33.0'
    - 'bioconductor-rhtslib >=2.0.0,<2.1.0'
    - 'bioconductor-rsamtools >=2.14.0,<2.15.0'
    - 'bioconductor-shortread >=1.56.0,<1.57.0'
    - r-base
    - r-bitops
    - r-hmisc
    - r-r2html
    - r-rcolorbrewer
    - r-rjava
    - r-sampling
    - r-sendmailr
    - r-snow
    - r-svmisc
    - r-xml
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic License 2.0'
  summary: 'ArrayExpress High Throughput Sequencing Processing Pipeline'
  description: 'RNA-Seq processing pipeline for public ArrayExpress experiments or local datasets'

