{% set version = "1.15.0" %}
{% set name = "OMICsPCAdata" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a2431a35117a8762f8bf86b81ee442b6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, kableExtra, rmarkdown
requirements:
  host:
    - 'bioconductor-multiassayexperiment >=1.24.0,<1.25.0'
    - r-base
  run:
    - 'bioconductor-multiassayexperiment >=1.24.0,<1.25.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-3
  summary: 'Supporting data for package OMICsPCA'
  description: 'Supporting data for package OMICsPCA'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

