{% set version = '1.0-24' %}

package:
  name: r-isogene
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/IsoGene_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/IsoGene/IsoGene_{{ version }}.tar.gz
  sha256: 19049382c45c870cd8e51e47ec1ec9b38bbfa1ff4af31fd5a07b5af57505953a

build:
  number: 9
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  run_exports:
    - {{ pin_subpackage('r-isogene', max_pin="x") }}

requirements:
  host:
    - r-base >=3.6.3
    - bioconductor-biobase
    - r-iso =0.0_18.1
    - bioconductor-affy
    - r-ff >=2.0.0
    - r-xtable
  run:
    - r-base >=3.6.3
    - bioconductor-biobase
    - r-iso =0.0_18.1
    - bioconductor-affy
    - r-ff >=2.0.0
    - r-xtable

test:
  commands:
    - $R -e "library('IsoGene')"

about:
  home: "https://CRAN.R-project.org/package=IsoGene"
  license: "GPL-3.0-or-later"
  summary: "Offers framework for testing for monotonic relationship between gene expression."
  license_family: GPL3
  license_file: "{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3"
  dev_url: "https://cran.r-project.org/src/contrib/Archive/IsoGene"
