{% set version = "1.15.0" %}
{% set name = "CopyNeutralIMA" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 5fdee9e6051aebcb432b3a39190ce577
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle,knitr,rmarkdown,minfi,conumee,minfiData
requirements:
  host:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - r-base
    - 'r-rdpack >=0.8'
  run:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - r-base
    - 'r-rdpack >=0.8'
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Copy Neutral Illumina Methylation Arrays'
  description: 'Provides a set of genomic copy neutral samples hybridized using Illumina Methylation arrays (450k and EPIC).'

