{% set version = "1.17.0" %}
{% set name = "HDCytoData" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 0264c9e4a88d12dc0588893ea2a990e6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, rmarkdown, Rtsne, umap, ggplot2, FlowSOM, mclust
requirements:
  host:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - 'bioconductor-flowcore >=2.10.0,<2.11.0'
    - 'bioconductor-summarizedexperiment >=1.28.0,<1.29.0'
    - r-base
  run:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - 'bioconductor-flowcore >=2.10.0,<2.11.0'
    - 'bioconductor-summarizedexperiment >=1.28.0,<1.29.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Collection of high-dimensional cytometry benchmark datasets in Bioconductor object formats'
  description: 'Data package containing a set of publicly available high-dimensional cytometry benchmark datasets, formatted into SummarizedExperiment and flowSet Bioconductor object formats, including all required metadata. Row metadata includes sample IDs, group IDs, patient IDs, reference cell population or cluster labels (where available), and labels identifying ''spiked in'' cells (where available). Column metadata includes channel names, protein marker names, and protein marker classes (cell type or cell state).'
  license_file: LICENSE

