{% set version = "1.11.0" %}
{% set name = "muscData" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: b0df5994604e48867035cfb2eb541e65
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, dplyr, DropletUtils, knitr, GEOquery, Matrix, matrixStats, methods, muscat, rmarkdown, R.utils, readxl, scater, scds, Seurat
requirements:
  host:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - 'bioconductor-singlecellexperiment >=1.20.0,<1.21.0'
    - r-base
  run:
    - 'bioconductor-experimenthub >=2.6.0,<2.7.0'
    - 'bioconductor-singlecellexperiment >=1.20.0,<1.21.0'
    - r-base
    - curl
    - bioconductor-data-packages>=20221103
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Multi-sample multi-group scRNA-seq data'
  description: 'Data package containing a collection of multi-sample multi-group scRNA-seq datasets in SingleCellExperiment Bioconductor object format.'
  license_file: LICENSE

