package:
  name: cap3
  version: '10.2011'

source:
  #- url: http://seq.cs.iastate.edu/CAP3/cap3.linux.x86_64.tar  # [linux]
  - url: https://iastate.box.com/s/q1f2ypcltu62bducv0wymy8cup9srvs1  # [linux]
    sha256: 86278775a71cba448f4f1bc782d8914594b5d9aebff1ad5e551e5f75ecb3a48b  # [linux]
    fn: cap3.linux.x86_64.tar  # [linux]
  #- url: http://seq.cs.iastate.edu/CAP3/cap3.macosx.intel64.tar  # [osx]
  - url: https://iastate.box.com/s/6qcx7gxe7bj6b1l2re3gi9x5xgin8br1  # [osx]
    sha256: 4b6e8fa6b39147b23ada6add080854ea9fadace9a9c8870a97ac79ff1c75338e  # [osx]
    fn: cap3.macosx.intel64.tar  # [osx]

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - cap3 2>&1 | grep "02/10/15"  # [linux]
    - cap3 2>&1 | grep "12/21/07"  # [osx]

about:
  home: http://seq.cs.iastate.edu/
  summary: 'DNA sequence assembly program.'
  license: Michigan Tech.
  authors: Xiaoqiu Huang and Anup Madan

extra:
  skip-lints:
    - should_not_be_noarch_source
